'use client';

import { useState } from 'react';
import type { BudgetSuggestion, ProviderMetadata } from '@/types';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Badge,
  Button,
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
  Separator,
} from '@/components/ui';
import { cn, formatCurrency } from '@/lib/utils';
import {
  Lightbulb,
  Sparkles,
  TrendingUp,
  AlertTriangle,
  ChevronDown,
  Target,
  Scale,
  Info,
  CheckCircle2,
  X,
} from 'lucide-react';

type Props = {
  suggestions: BudgetSuggestion[];
  providerMetadata?: ProviderMetadata;
  userQuery?: string | null;
};

function getPriorityFromImpact(impact: number): 'high' | 'medium' | 'low' {
  if (impact >= 200) return 'high';
  if (impact >= 50) return 'medium';
  return 'low';
}

function getPriorityConfig(priority: 'high' | 'medium' | 'low') {
  switch (priority) {
    case 'high':
      return {
        label: 'High Impact',
        variant: 'success' as const,
        icon: TrendingUp,
      };
    case 'medium':
      return {
        label: 'Medium Impact',
        variant: 'warning' as const,
        icon: Target,
      };
    case 'low':
      return {
        label: 'Low Impact',
        variant: 'secondary' as const,
        icon: Info,
      };
  }
}

function AIDisclaimer({ providerMetadata }: { providerMetadata?: ProviderMetadata }) {
  const [dismissed, setDismissed] = useState(false);

  if (!providerMetadata?.aiEnabled || dismissed) {
    return null;
  }

  return (
    <div className="relative rounded-lg border border-warning/30 bg-warning/10 p-4">
      <button
        onClick={() => setDismissed(true)}
        className="absolute right-2 top-2 rounded-full p-1 text-warning/70 transition-colors hover:bg-warning/20 hover:text-warning"
        aria-label="Dismiss disclaimer"
      >
        <X className="h-4 w-4" />
      </button>
      <div className="flex items-start gap-3 pr-6">
        <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-warning" />
        <div className="text-sm">
          <p className="font-semibold text-warning">AI-Generated Content</p>
          <p className="mt-1 text-warning/80">
            These suggestions are generated by AI and are for educational purposes only. They do not
            constitute financial advice. You remain fully responsible for any financial decisions.
          </p>
        </div>
      </div>
    </div>
  );
}

function UserQueryContext({ userQuery }: { userQuery?: string | null }) {
  if (!userQuery) {
    return null;
  }

  return (
    <div className="rounded-xl border border-primary/20 bg-gradient-to-r from-primary/10 to-accent/10 p-4">
      <p className="text-xs font-medium uppercase tracking-wide text-primary">Your Question</p>
      <p className="mt-1 text-sm text-foreground">&ldquo;{userQuery}&rdquo;</p>
      <p className="mt-2 text-xs text-muted-foreground">
        The suggestions below are tailored to answer your specific question.
      </p>
    </div>
  );
}

type SuggestionCardProps = {
  suggestion: BudgetSuggestion;
  index: number;
};

function SuggestionCard({ suggestion, index }: SuggestionCardProps) {
  const priority = getPriorityFromImpact(suggestion.expectedMonthlyImpact);
  const priorityConfig = getPriorityConfig(priority);
  const PriorityIcon = priorityConfig.icon;

  return (
    <Card
      className="group animate-fade-in-up transition-all hover:border-primary/30"
      style={{ animationDelay: `${index * 100}ms` }}
    >
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-start gap-3">
            <div className="rounded-full bg-primary/10 p-2">
              <Lightbulb className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle className="text-base">{suggestion.title}</CardTitle>
              <CardDescription className="mt-1">{suggestion.description}</CardDescription>
            </div>
          </div>
          <Badge variant={priorityConfig.variant} className="shrink-0">
            <PriorityIcon className="mr-1 h-3 w-3" />
            {priorityConfig.label}
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Impact */}
        <div className="flex items-center justify-between rounded-lg bg-success/10 px-4 py-3">
          <span className="text-sm font-medium text-success">Expected Monthly Impact</span>
          <span className="text-lg font-bold font-mono tabular-nums text-success">
            +{formatCurrency(suggestion.expectedMonthlyImpact)}
          </span>
        </div>

        {/* Rationale & Tradeoffs */}
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="details" className="border-none">
            <AccordionTrigger className="py-2 text-sm font-medium text-muted-foreground hover:text-foreground hover:no-underline">
              <div className="flex items-center gap-2">
                <Scale className="h-4 w-4" />
                View Details
              </div>
            </AccordionTrigger>
            <AccordionContent className="space-y-4 pt-2">
              {/* Rationale */}
              <div className="rounded-lg bg-muted/50 p-4">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  Rationale
                </div>
                <p className="mt-2 text-sm text-foreground">{suggestion.rationale}</p>
              </div>

              <Separator />

              {/* Tradeoffs */}
              <div className="rounded-lg bg-muted/50 p-4">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  <Scale className="h-3.5 w-3.5" />
                  Tradeoffs to Consider
                </div>
                <p className="mt-2 text-sm text-foreground">{suggestion.tradeoffs}</p>
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </CardContent>
    </Card>
  );
}

export function SuggestionsList({ suggestions, providerMetadata, userQuery }: Props) {
  const isAI = providerMetadata?.suggestionProvider === 'openai';

  if (!suggestions.length) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-12 text-center">
          <div className="rounded-full bg-muted p-4">
            <Lightbulb className="h-8 w-8 text-muted-foreground" />
          </div>
          <h3 className="mt-4 text-lg font-semibold text-foreground">No Suggestions Yet</h3>
          <p className="mt-2 max-w-sm text-sm text-muted-foreground">
            Upload a budget and answer clarification prompts to see tailored recommendations for
            improving your finances.
          </p>
        </CardContent>
      </Card>
    );
  }

  // Calculate total potential savings
  const totalPotentialSavings = suggestions.reduce(
    (sum, s) => sum + s.expectedMonthlyImpact,
    0
  );

  return (
    <div className="flex flex-col gap-6 animate-fade-in">
      {/* Header Card */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10">
                <Sparkles className="h-5 w-5 text-primary" />
              </div>
              <div>
                <CardTitle>{isAI ? 'AI-Powered Suggestions' : 'Personalized Suggestions'}</CardTitle>
                <CardDescription>
                  {suggestions.length} recommendation{suggestions.length !== 1 ? 's' : ''} to improve
                  your finances
                </CardDescription>
              </div>
            </div>
            {isAI && (
              <Badge variant="default" className="bg-primary/20 text-primary">
                <Sparkles className="mr-1 h-3 w-3" />
                Powered by AI
              </Badge>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Total Potential Savings */}
          <div className="rounded-xl border border-success/30 bg-gradient-to-r from-success/10 to-success/5 p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-success">Total Potential Monthly Savings</p>
                <p className="text-xs text-success/70">If all suggestions are implemented</p>
              </div>
              <p className="text-2xl font-bold font-mono tabular-nums text-success">
                +{formatCurrency(totalPotentialSavings)}
              </p>
            </div>
          </div>

          <UserQueryContext userQuery={userQuery} />
          <AIDisclaimer providerMetadata={providerMetadata} />
        </CardContent>
      </Card>

      {/* Suggestion Cards */}
      <div className="flex flex-col gap-4">
        {suggestions.map((suggestion, index) => (
          <SuggestionCard key={suggestion.id} suggestion={suggestion} index={index} />
        ))}
      </div>
    </div>
  );
}
