import type { BudgetSuggestion, ProviderMetadata } from '@/types';

type Props = {
  suggestions: BudgetSuggestion[];
  providerMetadata?: ProviderMetadata;
  userQuery?: string | null;
};

const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
});

function AIDisclaimer({ providerMetadata }: { providerMetadata?: ProviderMetadata }) {
  if (!providerMetadata?.aiEnabled) {
    return null;
  }

  return (
    <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3">
      <div className="flex items-start gap-2">
        <span className="text-amber-400" aria-hidden="true">
          ⚠️
        </span>
        <div className="text-xs text-amber-200">
          <p className="font-semibold">AI-Generated Content</p>
          <p className="mt-1 text-amber-200/80">
            These suggestions are generated by ChatGPT and are for educational purposes only. They
            do not constitute financial advice. You remain fully responsible for any financial
            decisions you make. The AI does not access your bank accounts or initiate any
            transactions.
          </p>
        </div>
      </div>
    </div>
  );
}

function UserQueryContext({ userQuery }: { userQuery?: string | null }) {
  if (!userQuery) {
    return null;
  }

  return (
    <div className="rounded-xl border border-indigo-500/20 bg-gradient-to-r from-indigo-500/10 to-purple-500/10 p-4">
      <p className="text-xs font-medium uppercase tracking-wide text-indigo-300">Your Question</p>
      <p className="mt-1 text-sm text-white">&ldquo;{userQuery}&rdquo;</p>
      <p className="mt-2 text-xs text-white/60">
        The suggestions below are tailored to answer your specific question.
      </p>
    </div>
  );
}

export function SuggestionsList({ suggestions, providerMetadata, userQuery }: Props) {
  const isAI = providerMetadata?.suggestionProvider === 'openai';

  if (!suggestions.length) {
    return (
      <div className="card">
        <p className="text-sm text-white/70">
          No suggestions yet. Upload a budget and answer clarification prompts to see tailored next
          steps.
        </p>
      </div>
    );
  }

  return (
    <div className="card flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold text-white">
          {isAI ? 'AI-Powered Suggestions' : 'Suggestions'}
        </h2>
        {isAI && (
          <span className="rounded-full bg-emerald-500/20 px-2 py-0.5 text-xs font-medium text-emerald-300">
            ChatGPT
          </span>
        )}
      </div>
      <UserQueryContext userQuery={userQuery} />
      <AIDisclaimer providerMetadata={providerMetadata} />
      <ul className="flex flex-col gap-3">
        {suggestions.map((suggestion) => (
          <li key={suggestion.id} className="rounded-lg border border-white/10 bg-white/5 p-4">
            <div className="flex flex-col gap-2">
              <div className="flex flex-col gap-1">
                <p className="text-base font-semibold text-white">{suggestion.title}</p>
                <p className="text-sm text-white/70">{suggestion.description}</p>
              </div>
              <p className="text-sm font-semibold text-emerald-200">
                Expected monthly impact: {currency.format(suggestion.expectedMonthlyImpact)}
              </p>
              <div className="mt-2 flex flex-col gap-2 rounded-lg bg-white/5 p-3 text-xs text-white/70">
                <p>
                  <span className="block font-semibold uppercase tracking-wider text-white/50">
                    Rationale
                  </span>
                  <span className="mt-1 block">{suggestion.rationale}</span>
                </p>
                <div className="h-px bg-white/10" />
                <p>
                  <span className="block font-semibold uppercase tracking-wider text-white/50">
                    Tradeoffs
                  </span>
                  <span className="mt-1 block">{suggestion.tradeoffs}</span>
                </p>
              </div>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}
